config/urls.py
from django.conf import settings
from django.urls import include, path, re_path
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import TemplateView
from django.views import defaults as default_views

from personal_website.crmblog import views as crmblog_views

urlpatterns = [
    path("", crmblog_views.BlogHomeView.as_view(), name="home"),
    path(
        "leds/",
        include("personal_website.leds.urls", namespace="leds"),
    ),
    path(
        "blog/",
        include("personal_website.crmblog.urls", namespace="crmblog"),
    ),
    path(
        "about/",
        include("personal_website.about.urls", namespace="about"),
    ),
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    # User management
    path(
        "users/",
        include("personal_website.users.urls", namespace="users"),
    ),
    path("accounts/", include("allauth.urls")),
    re_path(r'^markdownx/', include('markdownx.urls')),
] + static(
    settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
)

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

personal_website/about/urls.py
from django.urls import path

from . import views

app_name = "about"
urlpatterns = [
    path("founder-bios", view=views.BioListView.as_view(), name="bios"),
]

personal_website/leds/urls.py
from django.urls import path

from . import views

app_name = "leds"
urlpatterns = [
    path("json-data", view=views.JsonDataView, name="json-data"),
    path("control-panel", view=views.ControlPanelView.as_view(), name="led-ui"),
    path("update-json-data", view=views.AjaxUpdateJsonDataView, name="update-json-data"),
]

personal_website/users/urls.py
from django.urls import path

from . import views

app_name = "users"
urlpatterns = [
    path("", view=views.UserListView.as_view(), name="list"),
    path("~redirect/", view=views.UserRedirectView.as_view(), name="redirect"),
    path("~update/", view=views.UserUpdateView.as_view(), name="update"),
    path(
        "<str:username>",
        view=views.UserDetailView.as_view(),
        name="detail",
    ),
]

personal_website/about/models.py
from django.db import models
from django.conf import settings

from markdownx.models import MarkdownxField
from markdownx.utils import markdownify


class TimeStampedModel(models.Model):
    """
    An abstract base class model that provides self-updating
    "created" and "modified" fields.
    """
    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True


class Bio(TimeStampedModel):
    person = models.ForeignKey(settings.AUTH_USER_MODEL,
        null=True, on_delete=models.SET_NULL)
    photo = models.FileField(
        upload_to='static/images/about/bios')
    content = MarkdownxField(blank=True)

    def __str__(self):
        return self.person.first_name

    @property
    def formatted_markdown(self):
        return markdownify(self.content)

personal_website/crmblog/models.py
from django.db import models
from django.utils.html import strip_tags
from django.conf import settings

from autoslug import AutoSlugField

from markdownx.models import MarkdownxField
from markdownx.utils import markdownify

from taggit.managers import TaggableManager


class TimeStampedModel(models.Model):
    """
    An abstract base class model that provides self-updating
    "created" and "modified" fields.
    """
    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True


class Post(TimeStampedModel):
    title = models.CharField(max_length=255)
    tagline = models.CharField(max_length=255, blank=True)
    photo = models.FileField(
        upload_to='static/images/crmblog/post_photos')
    content = MarkdownxField(blank=True)
    slug = AutoSlugField(populate_from='title', blank=True)
    posted_date = models.DateTimeField(null=True)
    author = models.ForeignKey(settings.AUTH_USER_MODEL,
        null=True, on_delete=models.SET_NULL)

    tags = TaggableManager(blank=True)

    def __str__(self):
        return self.title

    # def save_model(self, request, obj, form, change):
    #   if not obj.pk:
    #       # Only set added_by during the first save.
    #       obj.author = request.user
    #   super().save_model(request, obj, form, change)

    @property
    def excerpt(self):
        """
        Returns the first 10 words of the post content.
        First convert markdown to html
        Then removes all html formatting
        """
        excerpt_list = strip_tags(self.content).split(" ")
        excerpt = " ".join(strip_tags(markdownify(self.content)).split(" ")[:10])
        if len(excerpt_list) > 10:
            excerpt += " ..."
        return excerpt

    @property
    def formatted_markdown(self):
        return markdownify(self.content)

    @property
    def pretty_date(self):
        return self.posted_date.date().strftime('%B %d, %Y')

personal_website/leds/models.py
from django.contrib.postgres.fields import JSONField
from django.db import models

class LedStrip(models.Model):
  """
  Stores information for a users LED strip. 
  Initially, just a JSON value to return
  """
  name = models.CharField(max_length=200)
  data = JSONField()

  def __str__(self):
    return self.name

personal_website/users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.urls import reverse
from django.utils.translation import ugettext_lazy as _


class User(AbstractUser):

    # First Name and Last Name do not cover name patterns
    # around the globe.
    name = models.CharField(_("Name of User"), blank=True, max_length=255)

    def __str__(self):
        return self.username

    def get_absolute_url(self):
        return reverse("users:detail", kwargs={"username": self.username})

personal_website/crmblog/forms.py
from django import forms
from django.core.mail import send_mail

from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Submit, Div, Field, ButtonHolder


class ContactForm(forms.Form):

    class Meta:
        fields = ['name', 'email', 'subject', 'message']

    def __init__(self, *args, **kwargs):
        super(ContactForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_method = 'post'
        self.fields['name'].label = False
        self.fields['email'].label = False
        self.fields['subject'].label = False
        self.fields['message'].label = False
        self.helper.layout = Layout (
            Div(
                Div(
                    Field(
                        'name',
                        id='contact-name',
                        value='',
                        placeholder='Name',
                    ),
                    css_class='6u 12u(mobile)'
                ),
                Div(
                    Field(
                        'email',
                        id='email',
                        value='',
                        placeholder='Email',
                    ),
                    css_class='6u 12u(mobile)'
                ),
                Div(
                    Field(
                        'subject',
                        id='subject',
                        value='',
                        placeholder='Subject',
                    ),
                    css_class='12u'
                ),
                Div(
                    Field(
                        'message',
                        id='message',
                        value='',
                        placeholder='Message',
                    ),
                    css_class='12u'
                ),
                Div(
                    ButtonHolder(
                        Submit(
                            'submit',
                            value='Send Message',
                            css_class='style1',
                        )
                    ),
                    css_class='12u',
                ),
                css_class='row uniform'
            )
        )

    name = forms.CharField(max_length=255, required=True)
    email = forms.EmailField(max_length=255, required=True)
    subject = forms.CharField(max_length=255, required=True)
    message = forms.CharField(
        max_length=1023,
        required=True,
        widget=forms.Textarea
    )

    def send_email(self):
        # send email using the self.cleaned_data dictionary
        subject = "[DC Contact] " + self.cleaned_data['subject']
        from_email = self.cleaned_data['email']
        to_email = ("derek.covey@gmail.com",)
        message = "Name: %s\nEmail: %s\n\n" % (
            self.cleaned_data['name'],
            from_email,
        )
        message += self.cleaned_data['message']

        send_mail(
            subject,
            message,
            from_email,
            to_email,
            fail_silently=False,
        )

personal_website/about/views.py
from django.shortcuts import render
from django.views.generic import ListView

from about.models import Bio


class BioListView(ListView):
  template_name = 'about/bios.html'
  model = Bio

  def get_queryset(self):
    queryset = super(BioListView, self).get_queryset()
    return queryset.order_by('created')

personal_website/crmblog/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import ListView, TemplateView, DetailView, FormView, View
from django.views.generic.edit import FormMixin
from django.contrib import messages

from crmblog.models import Post
from .forms import ContactForm


class EmailFormListView(FormMixin, ListView):
    def get_context_data(self, **kwargs):
        context = super(EmailFormListView, self).get_context_data(**kwargs)
        context['form'] = self.get_form()
        return context

    def form_valid(self, form):
        form.send_email()
        messages.success(self.request, 'Thanks for reaching out. Your message was sent successfully.')
        return super(EmailFormListView, self).form_valid(form)

    def post(self, request, *args, **kwargs):
        """
        Handle POST requests: instantiate a form instance with the passed
        POST variables and then check if it's valid.
        """
        form = self.get_form()
        if form.is_valid():
            return self.form_valid(form)
        else:
            return self.form_invalid(form)


class WebHomeView(EmailFormListView):
    model = Post
    template_name = 'crmblog/web_home.html'
    form_class = ContactForm
    success_url = reverse_lazy('crmblog:webhome')

    def get_queryset(self):
        queryset = super(WebHomeView, self).get_queryset()
        queryset = queryset.filter(tags__name__in=["web development"])
        return queryset.order_by('-created')[:4]     # Only need the 4 most recent posts


class WebPostListView(EmailFormListView):
    model = Post
    template_name = 'crmblog/web_archive.html'
    form_class = ContactForm
    success_url = reverse_lazy('crmblog:archive')

    def get_queryset(self):
        queryset = super(WebPostListView, self).get_queryset()
        queryset = queryset.filter(tags__name__in=["web development"])
        return queryset.order_by('-posted_date')


class PostDetailView(FormMixin, DetailView):
    model = Post
    template_name = 'crmblog/post_detail.html'
    form_class = ContactForm
    success_url = reverse_lazy('crmblog:webhome')

    def get_context_data(self, **kwargs):
        context = super(PostDetailView, self).get_context_data(**kwargs)
        context['form'] = self.get_form()
        return context

    def form_valid(self, form):
        form.send_email()
        messages.success(self.request, 'Thanks for reaching out. Your message was sent successfully.')
        return super(PostDetailView, self).form_valid(form)

    def post(self, request, *args, **kwargs):
        """
        Handle POST requests: instantiate a form instance with the passed
        POST variables and then check if it's valid.
        """
        form = self.get_form()
        if form.is_valid():
            return self.form_valid(form)
        else:
            return self.form_invalid(form)

    def get_success_url(self):
        return reverse_lazy('crmblog:post_detail', kwargs = {'slug': self.kwargs['slug']})


class BlogDemoView(TemplateView):
  template_name = 'crmblog/blog_demo.html'


class BlogHomeView(ListView):
  template_name = 'crmblog/blog_home.html'
  model = Post

  def get_queryset(self):
    queryset = super(BlogHomeView, self).get_queryset()
    return queryset.order_by('-posted_date')

personal_website/leds/views.py
from django.shortcuts import render
from django.views.generic import View, TemplateView, UpdateView
from django.http import JsonResponse, HttpResponse

from leds.models import LedStrip

import json

# class JsonDataView(View):
#     def get(self, request, *args, **kwargs):
#         data={"hello": "goodbye"}
#         return JsonResponse(data)

def JsonDataView(request):
  if request.method == "GET":
    obj=LedStrip.objects.get(pk=1)
    return JsonResponse(obj.data)

class ControlPanelView(TemplateView):
  template_name = 'leds/control-panel.html'

# class AjaxUpdateJsonDataView(UpdateView):
#   model = LedStrip
#   def get_object(self, queryset=None):
#     print('hello view')
#     super(AjaxUpdateJsonDataView, self).get_object(queryset=None)

def AjaxUpdateJsonDataView(request):
    if request.is_ajax() and request.method == 'POST':
      r = request.POST.dict()
      data = {
        "r": r["r"],
        "g": r["g"],
        "b": r["b"], 
      }
      # UPDATE: GIVE LEDSTRIP A NAME AND CONNECT IT TO A USER
      obj=LedStrip.objects.get(pk=1)
      obj.data=data
      obj.save()
      return JsonResponse({'result':'All is well on the luminous front'})
    else:
      return JsonResponse({'result':'Something went terribly wrong!'})

personal_website/users/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse
from django.views.generic import DetailView, ListView, RedirectView, UpdateView

from .models import User


class UserDetailView(LoginRequiredMixin, DetailView):
    model = User
    # These next two lines tell the view to index lookups by username
    slug_field = "username"
    slug_url_kwarg = "username"


class UserRedirectView(LoginRequiredMixin, RedirectView):
    permanent = False

    def get_redirect_url(self):
        return reverse("users:detail", kwargs={"username": self.request.user.username})


class UserUpdateView(LoginRequiredMixin, UpdateView):

    fields = ["name"]

    # we already imported User in the view code above, remember?
    model = User

    # send the user back to their own page after a successful update

    def get_success_url(self):
        return reverse("users:detail", kwargs={"username": self.request.user.username})

    def get_object(self):
        # Only get the User record for the user making the request
        return User.objects.get(username=self.request.user.username)


class UserListView(LoginRequiredMixin, ListView):
    model = User
    # These next two lines tell the view to index lookups by username
    slug_field = "username"
    slug_url_kwarg = "username"

personal_website/templates/common/partials/footer.html
<section id="footer" class="align-center">
    <ul class="icons">
      <li><a href="#" class="fa-twitter"><span class="label">Twitter</span></a></li>
      <li><a href="#" class="fa-facebook"><span class="label">Facebook</span></a></li>
      <li><a href="#" class="fa-instagram"><span class="label">Instagram</span></a></li>
      <li><a href="#" class="fa-rss"><span class="label">RSS</span></a></li>
      <li><a href="#" class="fa-envelope"><span class="label">Email</span></a></li>
    </ul>
    <p class="copyright">&copy; Untitled. Design: <a href="http://html5up.net">HTML5 UP</a>. Images: <a href="http://unsplash.com">Unsplash</a>.</p>
  </section>

personal_website/templates/common/partials/header.html
<!-- Header -->
  <header id="header">
    <h1><a href="{% url 'home' %}">The Verdance Project</a></h1>
    <nav class="links">
      <ul>
        <li><a href="{% url 'home' %}">Blog</a></li>
        <li><a href="#">Russian</a></li>
        <li><a href="{% url 'about:bios' %}">About</a></li>
        <li><a href="#">Contact Us</a></li>
      </ul>
    </nav>
    <nav class="main">
      <ul>
        <li class="search">
          <a class="fa-search" href="#search">Search</a>
          <form id="search" method="get" action="#">
            <input type="text" name="query" placeholder="Search" />
          </form>
        </li>
        <li class="menu">
          <a class="fa-bars" href="#menu">Menu</a>
        </li>
      </ul>
    </nav>
  </header>

<!-- Menu -->
  <section id="menu">

    <!-- Search -->
      <section>
        <form class="search" method="get" action="#">
          <input type="text" name="query" placeholder="Search" />
        </form>
      </section>

    <!-- Links -->
      <section>
        <ul class="links">
          <li>
            <a href="#">
              <h3>Blog</h3>
              <p>The story unfolds</p>
            </a>
          </li>
          <li>
            <a href="#">
              <h3>Russian</h3>
              <p>Flashcards and phrases</p>
            </a>
          </li>
          <li>
            <a href="{% url 'about:bios' %}">
              <h3>About</h3>
              <p>Meet the founders</p>
            </a>
          </li>
          <li>
            <a href="#">
              <h3>Contact Us</h3>
              <p>Send us a note</p>
            </a>
          </li>
        </ul>
      </section>

    <!-- Actions -->
      <section>
        <ul class="actions stacked">
          <li><a href="#" class="button large fit">Log In</a></li>
        </ul>
      </section>

  </section>

personal_website/templates/common/partials/old_site_footer.html
<!-- Footer -->
	<div id="footer-wrapper" class="wrapper">
		<div id="footer" class="container">
			<header class="style1">
				<h2>Thanks for reading!</h2>
				<p>
					Have any questions? Want to share a story	of your own or talk about
					a project? Drop me a line below.
				</p>
			</header>

			<hr />
			{% load crispy_forms_tags %}
			{% crispy form form.helper %}
		</div>
		<hr />



		<div id="copyright">
			<ul>
				<li><a href="https://github.com/djcroissant" class="icon alt"><span class="fab fa-github fa-2x"></span></li>
				<li><a href="https://www.linkedin.com/in/derek-covey-1928b07b/" class="icon alt"><span class="fab fa-linkedin-in fa-2x"></span></a></li>
				<li><a href="https://www.facebook.com/derek.covey" class="icon alt"><span class="fab fa-facebook-f fa-2x"></span></a></li>
			</ul>
			<br>
			<ul>
				<li>&copy; Derek Covey, 2018</li><li>CSS Design: <a href="http://html5up.net">HTML5 UP</a></li>
			</ul>
		</div>
	</div>

personal_website/templates/common/partials/scripts.html
{% load static %}

<script src="{% static 'js/common/html5up/jquery.min.js' %}"></script>
<script src="{% static 'js/common/html5up/browser.min.js' %}"></script>
<script src="{% static 'js/common/html5up/breakpoints.min.js' %}"></script>
<script src="{% static 'js/common/html5up/util.js' %}"></script>
<script src="{% static 'js/common/html5up/main.js' %}"></script>